dataset:
  name: celeba
  root: '/export/gts_usuarios/mariamartinezga/data'
  attr: # If None, we select all

model:
  likelihood: 'gauss'
  type_encoder: 'dcgan'
  type_decoder: 'cnnskip'
  beta: 15
  n_concepts: 40
  concept_inf: 'rep'   # 'rep' (repetition codes) or 'uncoded'
  sc_type: 'binary'         # If None, we do not include a side channel
  sc_inf:  'rep'            # If binary, indicate 'rep' or 'uncoded'. If sc_type='continuous' or sc_type=None, this will be ignored (can be None)
  sc_dim: 8                   # If sc_type=None, this will be ignored (can be None)

concept_code:
  bits_info: 40
  bits_code: 400
  root: './repetition_codes/'
  file: 'default'   # This will be ignored if concept_inf_type='uncoded'.

# This will be ignored if sc_type='continuous', sc_type=None. Bits of info are already specified in sc_dim
sc_code:
  bits_info: 8
  bits_code: 80
  root: './repetition_codes/'
  file: 'default'   # This will be ignored if concept_inf_type='uncoded'.

gpu: True

checkpoint:
  path: '/export/gts_usuarios/mariamartinezga/GitHub/CodedCBGM/checkpoints/celeba_sc_binary_8-80_200_epoch.pt'

log:
  wandb: True
  wandb_project: 'coded_cbgm'
  wandb_user: 'mariamartinezga'
