dataset:
  name: celeba
  root: '/home/martinez-garcia/data/'
  attr: # If None, we select all

model:
  likelihood: 'gauss'
  type_encoder: 'dcgan'
  type_decoder: 'cnnskip'
  beta: 15
  n_concepts: 40
  concept_inf: 'rep'   # 'rep' (repetition codes) or 'uncoded'
  sc_type: 'continuous'         # If None, we do not include a side channel
  sc_inf:            # If binary, indicate 'rep' or 'uncoded'. If sc_type='continuous' or sc_type=None, this will be ignored (can be None)
  sc_dim: 64                 # If sc_type=None, this will be ignored (can be None)

concept_code:
  bits_info: 40
  bits_code: 800
  root: '/home/martinez-garcia/CodedCBGM/repetition_codes/'
  file: 'default'   # This will be ignored if concept_inf_type='uncoded'.

# This will be ignored if sc_type='continuous', sc_type=None. Bits of info are already specified in sc_dim
sc_code:
  bits_info: 1
  bits_code: 1
  root: '/home/martinez-garcia/CodedCBGM/repetition_codes/'
  file: 'default'   # This will be ignored if concept_inf_type='uncoded'.

train:
  n_epochs: 200
  batch_size: 128
  lr: 0.00001
  n_samples: 10
  train_enc: True
  train_dec: True
  w_concept: 500
  w_orth: 0
  save: True
  
gpu: True

checkpoint:
  path: '/home/martinez-garcia/CodedCBGM/checkpoints/celeba_40-800_sc_continuous_64_whitening_wconcept_500_200_epoch_conduit.pt'

log:
  wandb: True
  wandb_project: 'coded_cbgm'
  wandb_user: 'mariamartinezga'
